### ISSUE TITLE
1.6.3 crashes dedicated server Forge 1.12.2 build 2838 -- NoSuchMethodError

### ISSUE THREAD

**Issue by kreezxil** [Pyrofab/SpawnerControl#7]
crash report:
http://paste.ubuntu.com/p/z48t2NVZjc/

fml server latest:
http://paste.ubuntu.com/p/Wsh3w7MyGd/

**Comment by Pyrofab** [comment]
Does this happen as well with 1.6.2 ?

**Comment by kreezxil** [comment]
1.6.2 does not crash, just tested it, with a dedicated server.

**Comment by Pyrofab** [comment]
Then I blame @Laike-Endaril

**Comment by Laike-Endaril** [comment]
I will go test right away then, and take a look at those logs

**Comment by Laike-Endaril** [comment]
Confirmed.  I cracked open the actual jar files for 1.6.2 and 1.6.3, and the code in that file differs.  I did not edit that code or any files that would've changed how it was built.

Hf @Pyrofab lol

**Comment by kreezxil** [comment]
Lol, you have Gremlins!!!

**Comment by Laike-Endaril** [comment]
It's just due to the change from SRG names to (now outdated) MCP names in some commits that were never part of a release (until now).  They just need to be changed back to SRG, probably.  Hopefully there's nothing else in those commits that will break things

**Comment by Laike-Endaril** [comment]
Actually, it seems not to be anything wrong with the code itself, but rather the build process?  I was able to build my own jar with the current code and it works fine on dedicated, on both 14.23.5.2768 and 14.23.5.2838.  Pyrofab and I will work this out on discord.

**Comment by Laike-Endaril** [comment]
These (the OP's issue, as well as the additional related one I mentioned) are now fixed in 1.6.3b

**Comment by NLBlackEagle** [comment]
Hey there and apologies for disturbing the peace here. I attempted to silently fix a shortcoming and push a PR but didn't got past OP's issue after forking and building the project:

If my guess is correct the following error log might look familiar: https://pastebin.com/tM5Zzt5P 
The fork runs fine in the development environment (run client - intellij) but fails to run outside the client and results in the above crash whereas a freshly downloaded .jar does work.

The whole reason I have forked this mod is because I'm working on a alternate RLCraft modpack (endorsed by shivaxi) and found out that potentialspawn within the NBT container doesn't tag entities with NBT_TAG_SPAWNER_POS. I wanted to figure out why this was, fix this and PR. Seemed simple enough until encountered the same issue as OP.
